apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakV3TWpBeApNVFUxTWpCYUZ3MDBNakV3TWpBeE1UVTFNakJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDakpTWTA3TFhiMTlIOGpQNS9jY3NjaUEvRTFEMFVKc1Y3U3grelJWWGxVU2lnTGNySgpoM3Z1ZVpWUHAvMVYvYTIxaGtBelVISFNkS3A4NFpPQ29iRmkzTUY0TUN3S3I5SXhWZ0x6NUs0aEt5VVd1Z0dsCldOWWtOQkNDRVAwaFdJRjdnRVZyZEtJelJGOXRKQU1LN1l4TmZpeCswUmNYY1NIQVh5ZVd5NEtFSXJOYjZia0gKRm9yQlBCckE4ZldTakZOWVRpYmdkaWxvTWErRFk4Q0NNcWZFVFBQRWJxRVpDeW5FV25SVGJqcmJ4bW1COFJCNwpwVXZDWisvYUp5UUM3T1d0TlkyYUVZcmJ5YlpvSE54RGMzLzRjZ3RHTFcvK21yc003Slg0amNXMFBycEtmM3pyCnd3THZMNEdlNXdjYVpSMTVIaXhQZzFHMTl1OWpYMzFjZitGdkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFBa3VYTW9pSFlyc2dGM3R3awpGbENrazB4eS9EQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFDbXJGWnVRSmxLRG5vcTBhNXB1KzBodWYraFRJCjV5eWp1TkVEYWMrMlhLRzdTTy8zT2N1QUNIWWIrMmZMK1hKNEx4VE9SdjN5b04ybGJoampWL0FVSVc5RTZMZ3kKMHlDSmpoM1dGQjhzbmk5U1JTbk05VXY5UTlCNU5TRGdrVG94cTFmSy9hUVc5SGR5bDRzdEZpOUhIODJrbDBTUwpaU21CZWNLbjJLSzJzWXFUOUNsRG1MbmFQK3NlUENENGNyUERQYVI5UjRSQ2t2MEh6c0FHZWNqNDhxSWgyZVAwCkNSTkZFb3BqYlNnQ0Y2UHQydHNEZE4xaE1JSjN2NWcybjZNZklHMFpsMFJ3aGVIdVBxT2ZaaUIrUDFLVXczdW8KMEJHSkw5d1l3UXpOcmVjQTNRdzc5THVpaTFVaGJ3dnVEb1VBTSsvYzBDMko1Qi8vYS9nbUE3MVR6UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://412f4ab4-7795-4764-84d7-025f0e61d2b9.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_7d793b146a84f3fc9bd1d3793d94ecc4803657729358fc9bdd9bd24eeb18e356
